version: '3.8'

services:
  db:
    container_name: mysql
    image: mysql:5.7  
    restart: always
    environment:
      - MYSQL_USER=${DB_USER}
      - MYSQL_ROOT_PASSWORD=${DB_PASSWORD}
      - MYSQL_DATABASE=${DB_NAME}
      - MYSQL_PASSWORD=${DB_PASSWORD}
    ports:
      - "3308:3306"  
    volumes:
      - mysql_data:/var/lib/mysql
    networks:
      - backend

  redis:
    container_name: redis
    image: redis:5.0
    restart: always
    ports:
      - "6379:6379"  
    command: redis-server --requirepass ${REDIS_PASSWORD}
    volumes:
      - redis_data:/data
    networks:
      - backend
volumes:
  mysql_data:  
  redis_data:  

networks: 
  backend: